version: "2"
services:
  redis:
    image: "redis:5.0"
    container_name: redis
    restart: unless-stopped
    volumes:
      - /persistent_data/com/liwmj/redis/data:/data
    network_mode: host
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]