version: "2"
services:
  gitlab:
    image: "twang2218/gitlab-ce-zh:10.8"
    container_name: gitlab
    restart: unless-stopped
    hostname: "gitlab.example.com"
    environment:
      TZ: "Asia/Shanghai"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['rack_attack_git_basic_auth'] = { 'enabled' => true, 'ip_whitelist' => ["127.0.0.1", "47.99.160.104"], 'maxretry' => 300, 'findtime' => 5, 'bantime' => 60 }
        # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
        # 比如下面的电子邮件的配置：
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.mxhichina.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "liwangmijia@wonlycloud.com"
        gitlab_rails['smtp_password'] = "xxxxx"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_domain'] = "wonlycloud.com"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'liwangmijia@wonlycloud.com'
        gitlab_rails['git_user_email'] = 'liwangmijia@wonlycloud.com'
        gitlab_rails['gitlab_email_dispaly_name'] = 'Wonly'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@wonlycloud.com'
        gitlab_rails['gitlab_default_theme'] = 2
        # gitlab_rails['gitlab_shell_ssh_port'] = 40022
        # nginx['listen_port'] = 44380
        # nginx['redirect_http_to_https'] = true
        # nginx['ssl_certificate'] = "/etc/gitlab/ssl/dev.mdde.com.crt"
        # nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/server.key"
        # nginx['proxy_set_headers'] = {
        #     "X-Forwarded-Proto" => "https",
        #     "X-Forwarded-Ssl" => "on",
        # }
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - /persistent_data/gitlab/config:/etc/gitlab
      - /persistent_data/gitlab/data:/var/opt/gitlab
      - /persistent_data/gitlab/logs:/var/log/gitlab
